function [Knots_n] = linear_2d_grid_from_displ(T, Spacing, imsz)
    ksz = ceil(imsz ./ Spacing) + 1;
    Knots_n =...
        T([1, 1+Spacing(1):Spacing(1):(ksz(1)-1)*Spacing(1), imsz(1)], ...
          [1, 1+Spacing(2):Spacing(2):(ksz(2)-1)*Spacing(2), imsz(2)], ...
          :);
end